In [1]:
#Import numpy and create 2 ndarrays with the same length and another one with a different length (3 arrays in total).
import numpy as np
a = np.array([2,3,4])
b = np.array([5,6,7])
c = np.array([(1,2,3), (4,5,6)])
print(a)
print(b)
print(c)

[2 3 4]
[5 6 7]
[[1 2 3]
 [4 5 6]]


In [4]:
#Perform at least three operations of your choice on the arrays with the same size.

d= a +b
print(d)
print(a.sum())
print(a.min())
print(a.max())


[ 7  9 11]
9
2
4


In [7]:
#Perform at least three operations of your choice on one element from two arrays. 
print(a*b)
print(c *3)
print(np.add(b, c))

[10 18 28]
[[ 3  6  9]
 [12 15 18]]
[[ 6  8 10]
 [ 9 11 13]]


In [13]:
#Create four variables containing a string, integer, float, and boolean and try to cast them to (in order) boolean, 
#float, integer, and string. 
a ='String'
print(type(a))
b = 100
print(type (b))
c = 10.10
print(type (c))
d = (a!=b)
print(type(d))

e = '5'
print(e)

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [1]:
#Create an array containing numbers 1 to 10. Iterate through the array using a for loop. 
#Inside the for loop use some if statement to print the numbers "four" instead of 4 and "eight" instead of 8, 
#otherwise print the digit number. 

a = [1,2,3,4,5,6,7,8,9,10]

for var in a:
    if var == 4:
        print('four')
    elif var == 8:
        print('eight')
    else:
        print(var)
    
    

1
2
3
four
5
6
7
eight
9
10


In [5]:
#Create a tuple containing 3 numbers and a list containing 5 numbers.

a = (1,2,3)
b = [4,5,6,7,8]

#Unpack the tuple into 3 different variables and print them

c,d,e = a
print(c,d,e)

#Then try to remove an element from the list

b.remove(4)

#and instead insert one of the variables that were the result of unpacked tuple.

b.append(c)
print(b)
#Finally, slice and sort the first 3 elements of the list. 

b.sort()
f = b[0:3]
print(f)

1 2 3
[5, 6, 7, 8, 1]
[1, 5, 6]


In [6]:
#Create a dictionary with these keys: 'int', 'float', 'string', 'boolean', 'list', 'set', 'tuple' and 'dict' 
#and for each key, assign the value of that specific type. For instance, you should create a temporary small 
#dictionary to assign to the 'dict'. 

a = { "i":1, "j":2 }

b = { "int":1, "float":2.1,"string":'My String', "boolean":'True',"list":[1,2,3], "set":(1,2,3),"tuple":(1,2),"dict":a }

print(b.keys())
print(b.values())


dict_keys(['int', 'float', 'string', 'boolean', 'list', 'set', 'tuple', 'dict'])
dict_values([1, 2.1, 'My String', 'True', [1, 2, 3], (1, 2, 3), (1, 2), {'i': 1, 'j': 2}])


In [15]:
#Create a list containing letters 'a' to 'f', then using a for loop and proper sequence function, produce the following

a = ['a','b','c','d','e','f']

#3 --> a 

for index,letter in enumerate(a):
    index += 3
    print(str(index) + '-->' + str(letter))
    
    

3-->a
4-->b
5-->c
6-->d
7-->e
8-->f


In [18]:
#By copying the previous list, create a new variable containing the same 'a' to 'f' elements from the previous list. 
#Change an element in one of the variables and make sure the other doesn't change. 

b = a.copy()
print(b)
print(a)
b[0] = 'g'
print(b)
print(a)

['a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']
['g', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']


In [23]:
#Create a variable containing a tuple object. Then try to change its first element the way you change an element in a list and 
#see what kind of error you will get. Then try to catch handle the error and instead of 
#the error print "Tuples are immutable :)" 

t = (1,2,3)
try:
    t[0] = 4
except TypeError:
    print ('Tuples are immutable')


Tuples are immutable
